-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:Chimei Innolux Corporation 0x1441",
  mode = "1920x1200@60",
  position = "0x0",
  scale = 1,
  bitdepth = 10,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
